export { default as ButtonWithCustomStyles } from "./Other/Button/ButtonWithCustomStyles";
export { default as UsersDataFormInput } from "./Other/Input//UserDataFormInput";
export { Text } from "./Other/SimpleText/Text";
export { default as Model } from "./Other/Modal/Modal";
export { default as SelectMenu } from "./Other/Select/SelectMenu";
export { default as SelectMenuActive } from "./Other/Select/SelectMenuActive";
export { default as ButtonCustomWidth } from "./Other/Button/ButtonCustomWidth";
export { default as ButtonWithBlueBack } from "./Other/Button/ButtonWithBlueBack";
export { ParaCustom } from "./Other/SimpleText/ParaCustom";
export { default as OnlyIconButton } from "./Other/Button/OnlyIconButton";
export { default as SelectPagination } from "./Other/Select/SelectPagination";
export { default as SelectGraph } from "./Other/Select/SelectGraph";
export { default as SimpleTable } from "./Other/Tables/SimpleTable";
export { default as TextAreaSimple } from "./Other/Input/TextAreaSimple";
